export const MOCK_YIELDS = [
  {
    id: "ethereum-lido-staking",
    apy: 0.0365,
    network: "ethereum",
    provider: "lido",
    type: "liquid-staking",
    token: { name: "Staked Ether", symbol: "stETH" },
  },
  {
    id: "ethereum-aave-v3-usdc-lending",
    apy: 0.0512,
    network: "ethereum",
    provider: "aave-v3",
    type: "lending",
    token: { name: "USD Coin", symbol: "USDC" },
  },
  {
    id: "ethereum-aave-v3-eth-lending",
    apy: 0.0238,
    network: "ethereum",
    provider: "aave-v3",
    type: "lending",
    token: { name: "Wrapped Ether", symbol: "WETH" },
  },
  {
    id: "ethereum-rocketpool-staking",
    apy: 0.0341,
    network: "ethereum",
    provider: "rocketpool",
    type: "liquid-staking",
    token: { name: "Rocket Pool ETH", symbol: "rETH" },
  },
  {
    id: "ethereum-morpho-usdt-lending",
    apy: 0.0678,
    network: "ethereum",
    provider: "morpho",
    type: "lending",
    token: { name: "Tether", symbol: "USDT" },
  },
  {
    id: "polygon-aave-v3-usdc-lending",
    apy: 0.0423,
    network: "polygon",
    provider: "aave-v3",
    type: "lending",
    token: { name: "USD Coin", symbol: "USDC" },
  },
  {
    id: "polygon-aave-v3-matic-lending",
    apy: 0.0189,
    network: "polygon",
    provider: "aave-v3",
    type: "lending",
    token: { name: "Polygon", symbol: "MATIC" },
  },
  {
    id: "arbitrum-aave-v3-usdc-lending",
    apy: 0.0567,
    network: "arbitrum",
    provider: "aave-v3",
    type: "lending",
    token: { name: "USD Coin", symbol: "USDC" },
  },
  {
    id: "arbitrum-gmx-glp-vault",
    apy: 0.1245,
    network: "arbitrum",
    provider: "gmx",
    type: "vault",
    token: { name: "GLP", symbol: "GLP" },
  },
  {
    id: "base-aave-v3-usdc-lending",
    apy: 0.0634,
    network: "base",
    provider: "aave-v3",
    type: "lending",
    token: { name: "USD Coin", symbol: "USDC" },
  },
  {
    id: "base-aerodrome-eth-usdc-lp",
    apy: 0.2156,
    network: "base",
    provider: "aerodrome",
    type: "liquidity-pool",
    token: { name: "ETH-USDC LP", symbol: "ETH-USDC" },
  },
  {
    id: "solana-marinade-staking",
    apy: 0.0721,
    network: "solana",
    provider: "marinade",
    type: "liquid-staking",
    token: { name: "Marinade SOL", symbol: "mSOL" },
  },
  {
    id: "solana-jito-staking",
    apy: 0.0789,
    network: "solana",
    provider: "jito",
    type: "liquid-staking",
    token: { name: "Jito SOL", symbol: "jitoSOL" },
  },
  {
    id: "avalanche-aave-v3-usdc-lending",
    apy: 0.0398,
    network: "avalanche",
    provider: "aave-v3",
    type: "lending",
    token: { name: "USD Coin", symbol: "USDC" },
  },
  {
    id: "avalanche-benqi-avax-staking",
    apy: 0.0534,
    network: "avalanche",
    provider: "benqi",
    type: "liquid-staking",
    token: { name: "Staked AVAX", symbol: "sAVAX" },
  },
  {
    id: "bnb-venus-usdc-lending",
    apy: 0.0456,
    network: "bnb",
    provider: "venus",
    type: "lending",
    token: { name: "USD Coin", symbol: "USDC" },
  },
  {
    id: "bnb-pancakeswap-cake-staking",
    apy: 0.0312,
    network: "bnb",
    provider: "pancakeswap",
    type: "staking",
    token: { name: "PancakeSwap", symbol: "CAKE" },
  },
  {
    id: "optimism-aave-v3-usdc-lending",
    apy: 0.0489,
    network: "optimism",
    provider: "aave-v3",
    type: "lending",
    token: { name: "USD Coin", symbol: "USDC" },
  },
  {
    id: "ethereum-eigenlayer-restaking",
    apy: 0.0456,
    network: "ethereum",
    provider: "eigenlayer",
    type: "restaking",
    token: { name: "Restaked ETH", symbol: "eETH" },
  },
  {
    id: "ethereum-compound-v3-usdc-lending",
    apy: 0.0534,
    network: "ethereum",
    provider: "compound",
    type: "lending",
    token: { name: "USD Coin", symbol: "USDC" },
  },
  {
    id: "cosmos-cosmoshub-staking",
    apy: 0.1923,
    network: "cosmos",
    provider: "cosmoshub",
    type: "staking",
    token: { name: "Cosmos", symbol: "ATOM" },
  },
  {
    id: "ethereum-spark-dai-lending",
    apy: 0.0823,
    network: "ethereum",
    provider: "spark",
    type: "lending",
    token: { name: "DAI", symbol: "DAI" },
  },
];

export const MOCK_NETWORKS = [
  { id: "ethereum", name: "Ethereum" },
  { id: "polygon", name: "Polygon" },
  { id: "arbitrum", name: "Arbitrum" },
  { id: "base", name: "Base" },
  { id: "optimism", name: "Optimism" },
  { id: "solana", name: "Solana" },
  { id: "avalanche", name: "Avalanche" },
  { id: "bnb", name: "BNB Chain" },
  { id: "cosmos", name: "Cosmos" },
];
